doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
        # Раскомментируйте для PostgreSQL:
        # server_version: '16'
        # Для MySQL/MariaDB:
        server_version: '8.0'
        logging: true
        profiling: true

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        enable_lazy_ghost_objects: true
        proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'

        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: true

                metadata_cache_driver:
                            type: pool
                            pool: doctrine.metadata_cache_pool

                query_cache_driver:
                            type: pool
                            pool: doctrine.query_cache_pool

                result_cache_driver:
                            type: pool
                            pool: doctrine.result_cache_pool

                mappings:
                    App:
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'


