framework:
    messenger:


        transports:


        default_bus: messenger.bus.default

        buses:
            messenger.bus.default: []

        routing:


            # Route your messages to the transports
            # 'App\Message\YourMessage': async
