services:
  php:
    build:
      context: ./docker/php
    environment:
      DATABASE_URL: "mysql://root:root@mysql:3306/sentihell?serverVersion=8.0.41"
      APP_ENV: test
      REDIS_URL: redis://redis:6379
      APP_SECRET: testsecret
    volumes:
      - .:/var/www
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sentihell
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10