# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    gallery_max_per_page: 50
    project_temp_dir: '%kernel.project_dir%/backend/var/tmp/'
    images_s_dir: '%kernel.project_dir%/public/uploads/images/s/'
    images_m_dir: '%kernel.project_dir%/public/uploads/images/m/'
    images_l_dir: '%kernel.project_dir%/public/uploads/images/l/'
services:
    App\EventSubscriber\AdminLogoutSubscriber:
        tags: [ kernel.event_subscriber ]

    redis_connection:
        class: Redis
        factory: [ 'Symfony\Component\Cache\Adapter\RedisAdapter', 'createConnection' ]
        arguments:
            - 'redis://%env(REDIS_HOST)%:%env(REDIS_PORT)%?timeout=0.5&connect_timeout=0.3'
            - { retry_interval: 1, retry_timeout: 5 } # Параметры повтора

    App\EventSubscriber\AssertionExceptionSubscriber:
        tags:
            - { name: kernel.event_subscriber }
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
