# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    gallery_max_per_page: 50
    project_temp_dir: '%env(TEMP_DIR)%'
    images_s_dir: '%kernel.project_dir%/public/uploads/images/s/'
    images_m_dir: '%kernel.project_dir%/public/uploads/images/m/'
    images_l_dir: '%kernel.project_dir%/public/uploads/images/l/'
    env(NGINX_BASE_URL): 'http://nginx'
    nginx_cache_path: '/var/cache/nginx/client'
services:
    App\Service\Interface\GalleryDataProviderInterface:
        class: App\Service\GalleryService
        arguments:
            - '@doctrine.dbal.default_connection'

    App\EventSubscriber\AdminLogoutSubscriber:
        tags: [ kernel.event_subscriber ]

    Redis:
        class: Redis
        factory: [ 'Symfony\Component\Cache\Adapter\RedisAdapter', 'createConnection' ]
        arguments:
            - '%env(REDIS_URL)%'

    App\EventSubscriber\AssertionExceptionSubscriber:
        tags:
            - { name: kernel.event_subscriber }
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.



    # Репозитории
    App\Repository\Interface\ImageRepositoryInterface: '@App\Repository\ImageRepository'

    # Сервисы
    App\Service\Interface\VideoProcessorInterface: '@App\Service\VideoProcessor'
    App\Service\Interface\CacheManagerInterface: '@App\Service\CachePurgerService'
    App\Service\Interface\ImageStorageInterface: '@App\Service\ImageFileManager'
    App\Service\Interface\DtoMapperInterface: '@App\Service\DtoMapperService'
    App\Service\Interface\ErrorHandlerInterface: '@App\Service\ErrorService'
    App\Service\Interface\CachePurgerInterface: '@App\Service\CachePurgerService'
    App\Service\Interface\MultipartParserInterface: '@App\Service\MultipartRequestParser'
    App\Repository\Interface\VideoRepositoryInterface: '@App\Repository\VideoRepository'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    App\Service\CachePurgerService:
        arguments:
                $nginxCachePath: '%nginx_cache_path%'
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Service\ImageFileManager:
        arguments:
            $sDir: '%images_s_dir%'
            $mDir: '%images_m_dir%'
            $lDir: '%images_l_dir%'
            $fs: '@filesystem'

    App\Service\DtoMapperService:
        arguments:
            $router: '@router'
